config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  belongs_to :gender
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :product_colors
  has_many :products, through: :product_colors
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :products
  has_many :categories
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :gender
  belongs_to :category

  has_many :product_sizes, dependent: :destroy
  has_many :sizes, through: :product_sizes

  has_many :product_colors, dependent: :destroy
  has_many :colors, through: :product_colors
  has_many_attached :photos

end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  belongs_to :product
  belongs_to :color
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  belongs_to :size
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :product_sizes
  has_many :products, through: :product_sizes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many_attached :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # Obtén todos los productos disponibles.
    available_products = Product.where(availability: "Disponible")

    # Obtén 3 productos aleatorios de los disponibles.
    random_products = available_products.sample(5)

    # Asigna los productos aleatorios a la variable @initial para que estén disponibles en la vista.
    @initial = random_products
    @first_two_products = @initial.first(2)
  end
end
## <div class="information-home">
##   <div class="row">
##     <div class="information-content m-2 col-lg-10 col-12">
##       <h3 class="title">¿Quiénes somos?</h3>
##       <p>Somos una empresa ubicada en Cúcuta, especializada en la venta al por mayor y al detal de pantalones para damas y caballeros, así como chalecos exclusivos para mujeres. Nuestra pasión por la moda y la atención a los detalles nos impulsan a ofrecer productos de alta calidad que reflejen tu estilo único y te hagan sentir confiado en cada ocasión. Desde jeans versátiles hasta shorts y bermudas de moda, nuestra amplia gama de opciones te permite expresar tu personalidad a través de tu vestimenta.</p>
##     </div>
##     <div class="col-lg-2 col-12 d-none d-md-block">
##       <%= cl_image_tag User.first.photos[3].url, class: "banner-image imagen-2 side-image" %>
##     </div>
##   </div>
## </div>

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy

    redirect_to products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :price,
      :stock,
      :availability,
      :gender_id,
      :category_id,
      photos: [],
      color_ids: [],   # Para permitir múltiples colores asociados
      size_ids: []     # Para permitir múltiples tallas asociadas
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # def index
  #   # Encuentra los géneros 'Dama' y 'Caballero'
  #   @lady = Gender.find_by(name: 'Dama')
  #   @gentleman = Gender.find_by(name: 'Caballero')

  #   # Filtrar los productos según el parámetro 'gender'
  #   if params[:gender] == 'lady'
  #     @products = Product.where(gender: @lady)  # Filtra por el género 'Dama'
  #     @selected_gender = @lady  # Marca 'Dama' como género seleccionado
  #   elsif params[:gender] == 'gentleman'
  #     @products = Product.where(gender: @gentleman)  # Filtra por el género 'Caballero'
  #     @selected_gender = @gentleman  # Marca 'Caballero' como género seleccionado
  #   end
  # end

  def index
    @lady = Gender.find_by(name: 'Dama')
    @gentleman = Gender.find_by(name: 'Caballero')

    if params[:gender] == 'lady'
      @products = Product.where(gender: @lady)
      @selected_gender = @lady
    elsif params[:gender] == 'gentleman'
      @products = Product.where(gender: @gentleman)
      @selected_gender = @gentleman
    end

    @categories = @selected_gender.categories.distinct
  end


  def show
  end

  def new
    @colors = Color.all
    @product = Product.new
    @categories = Category.all # Asegúrate de definir correctamente @categories
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    @colors = Color.all
  end

  def update
    @colors = Color.all
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :price,
      :ref,
      :availability,
      :gender_id,
      :category_id,
      :wholesale_price,
      :quantity,
      photos: [],
      color_ids: [],   # Para permitir múltiples colores asociados
      size_ids: []     # Para permitir múltiples tallas asociadas
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tendencias Y Diseños</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="<%= asset_path('T&D.ico') %>">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner d-flex justify-content-center align-items-center justify-content-evenly">
  <% user_photos = User.first.photos %>
  <%= cl_image_tag user_photos[0].url, class: "banner-image imagen-1" %>
  <%= cl_image_tag user_photos[1].url, class: "banner-image logo-image" %>
  <%= cl_image_tag user_photos[2].url, class: "banner-image imagen-2" %>
</div>



<div class="product-initial">
  <h3 class="title" >Productos Destacados</h3>
  <div class="featured">
    <% @initial.each do |product| %>
      <div class="card" data-categories="<%= product.category.category_type %>">
        <a href="<%= product_path(product) %>">
          <% if product.photos.any? %>
            <%= cl_image_tag product.photos.first.url, class: "card-img-top product-image" %>
          <% else %>
            <%= image_tag "logo_negro.png", class: "card-img-top product-image" %>
          <% end %>
        </a>
        <div class="card-body">
          <h6 class="card-text"><strong><%= product.name %></strong></h6>
          <div class="price"><%= number_to_currency(product.price, unit: '$', format: '%u%n') %></div>
        </div>
      </div>
    <% end %>
  </div>
    <div class="small">
    <% @first_two_products.each do |product| %>
      <div class="card" data-categories="<%= product.category.category_type %>">
        <a href="<%= product_path(product) %>">
          <% if product.photos.any? %>
            <%= cl_image_tag product.photos.first.url, class: "card-img-top product-image" %>
          <% else %>
            <%= image_tag "logo_negro.png", class: "card-img-top product-image" %>
          <% end %>
        </a>
        <div class="card-body">
          <h6 class="card-text"><strong><%= product.name %></strong></h6>
          <div class="price"><%= number_to_currency(product.price, unit: '$', format: '%u%n') %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="questions p-5">
  <h1 class="question py-3">Preguntas Frecuentes</h1>
  <h1 class="valor py-4">¿QUÉ VALOR TIENE EL ENVÍO?</h1>
  <p>el precio del envío depende de la ciudad el número de prendas. manejamos contraentrega (Servientrega, interrapidisimo y envía).</p>
  <br>
  <h1 class="valor py-4">¿CUÁNTO TIEMPO TARDA EN LLEGAR MI PEDIDO?</h1>
  <p class="delivery">Los pedidos tardan en llegar entre 3 y 8 días fuera de Cúcuta.</p>

  <!-- Barra separadora -->
  <div class="separator"></div>

  <!-- Contenedor de los enlaces centrados -->
  <div class="links-container">
    <a href="https://www.instagram.com/tyd_jeans/" target="_blank" class="instagram-link">
      <i class="fab fa-instagram"></i>
      <p class="siguenos">@tyd_jeans</p>
    </a>
    <a href="https://api.whatsapp.com/send?phone=573155127061&text=<%= CGI.escape("Hola, somos TYD. ¿En qué podemos asesorarte?") %>" target="_blank" class="instagram-link">
      <i class="fa-brands fa-whatsapp"></i>
      <p class="siguenos">+57 315 512 7016 | Ventas</p>
    </a>
    <a href="https://api.whatsapp.com/send?phone=573004233454&text=<%= CGI.escape("Hola, somos TYD. ¿En qué podemos asesorarte?") %>" target="_blank" class="instagram-link">
      <i class="fa-brands fa-whatsapp"></i>
      <p class="siguenos">+57 300 423 3454 | Gerencia</p>
    </a>
    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "instagram-link" do %>
        <i class="fa-regular fa-user"></i>
        <p class="siguenos">Cerrar sesion</p>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "instagram-link" do %>
        <i class="fa-regular fa-user"></i>
        <p class="siguenos">Eres propietario?</p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/_form.html.erb
<% if user_signed_in? %>
  <div class="container shadow mt-3 p-3 w-50">
    <% if product.new_record? %>
      <h5 class="text-center">Nuevo Producto</h5>
    <% else %>
      <h5 class="text-center">Editar Producto</h5>
    <% end %>
    <%= simple_form_for product, html: { multipart: true, id: "product_form" } do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :ref %>
      <%= f.input :availability, collection: ['Disponible', 'No disponible'] %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>

      <!-- Agregar la entrada para seleccionar el género -->
      <div class="form-group">
        <label>Género</label><br>
        <%= f.collection_radio_buttons :gender_id, Gender.all, :id, :name %>
      </div>

      <!-- Agregar la entrada para seleccionar la categoría para dama -->
      <div class="form-group category-fields lady"> <!-- Para categorías de Dama -->
        <label>Categorías para Dama</label><br>
        <%= f.collection_select :category_id, Category.where(gender_id: Gender.find_by(name: 'Dama').id), :id, :category_type %>
      </div>

      <!-- Agregar la entrada para seleccionar la categoría para caballero -->
      <div class="form-group category-fields gentleman"> <!-- Para categorías de Caballero -->
        <label>Categoría para Caballero</label><br>
        <%= f.collection_select :category_id, Category.where(gender_id: Gender.find_by(name: 'Caballero').id), :id, :category_type %>
      </div>

      <div class="form-group">
        <label>Colores</label>
        <div class="btn-group-toggle" data-toggle="buttons">
          <% @colors.each do |color| %>
            <% text_color = ["Negro", "Azul marino", "Verde Oliva"].include?(color.name) ? "white" : "black" %>
            <label class="btn btn-outline-primary m-2" style="background-color: <%= color.hex_code %>; color: <%= text_color %>">
              <%= f.check_box :color_ids, { multiple: true }, color.id, nil %>
              <%= color.name %>
            </label>
          <% end %>
        </div>
      </div>
      <br>
      <label>Tallas</label>
      <div class="form-group d-flex flex-wrap">
        <%= f.collection_check_boxes :size_ids, Size.all, :id, :measure do |b| %>
          <div class="form-check mb-2 mr-2">
            <%= b.check_box class: "form-check-input" %>
            <%= b.label class: "form-check-label" %>
          </div>
        <% end %>
      </div>


      <div class="row d-flex justify-content-center">
        <div class="col-2">
          <%= f.submit product.new_record? ? "Crear" : "Actualizar", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h1 class="text-center">Solo los propietarios pueden crear nuevos productos.</h1>
<% end %>

app/views/products/_formgentleman.html.erb
<% if user_signed_in? %>
  <div class="container shadow mt-3 p-3 w-50">
    <% if product.new_record? %>
      <h5 class="text-center">Nuevo Producto</h5>
    <% else %>
      <h5 class="text-center">Editar Producto</h5>
    <% end %>
    <%= simple_form_for product, html: { multipart: true, id: "product_form" } do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :ref %>
      <%= f.input :availability, collection: ['Disponible', 'No disponible'] %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>

      <!-- Agregar la entrada para seleccionar el género -->
      <div class="form-group">
        <label>Género</label><br>
        <%= f.collection_radio_buttons :gender_id, Gender.all, :id, :name %>
      </div>

      <!-- Agregar la entrada para seleccionar la categoría para caballero -->
      <div class="form-group category-fields gentleman"> <!-- Para categorías de Caballero -->
        <label>Categoría para Caballero</label><br>
        <%= f.collection_select :category_id, Category.where(gender_id: Gender.find_by(name: 'Caballero').id), :id, :category_type %>
      </div>

      <div class="form-group">
        <label>Colores</label>
        <div class="btn-group-toggle" data-toggle="buttons">
          <% @colors.each do |color| %>
            <% text_color = ["Negro", "Azul marino", "Verde Oliva"].include?(color.name) ? "white" : "black" %>
            <label class="btn btn-outline-primary m-2" style="background-color: <%= color.hex_code %>; color: <%= text_color %>">
              <%= f.check_box :color_ids, { multiple: true }, color.id, nil %>
              <%= color.name %>
            </label>
          <% end %>
        </div>
      </div>
      <br>
      <label>Tallas</label>
      <div class="form-group d-flex flex-wrap">
        <%= f.collection_check_boxes :size_ids, Size.all, :id, :measure do |b| %>
          <div class="form-check mb-2 mr-2">
            <%= b.check_box class: "form-check-input" %>
            <%= b.label class: "form-check-label" %>
          </div>
        <% end %>
      </div>


      <div class="row d-flex justify-content-center">
        <div class="col-2">
          <%= f.submit product.new_record? ? "Crear" : "Actualizar", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h1 class="text-center">Solo los propietarios pueden crear nuevos productos.</h1>
<% end %>

app/views/products/_formlady.html.erb
<% if user_signed_in? %>
  <div class="container shadow mt-3 p-3 w-50">
    <% if product.new_record? %>
      <h5 class="text-center">Nuevo Producto</h5>
    <% else %>
      <h5 class="text-center">Editar Producto</h5>
    <% end %>
    <%= simple_form_for product, html: { multipart: true, id: "product_form" } do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :ref %>
      <%= f.input :availability, collection: ['Disponible', 'No disponible'] %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>

      <!-- Agregar la entrada para seleccionar el género -->
      <div class="form-group">
        <label>Género</label><br>
        <%= f.collection_radio_buttons :gender_id, Gender.all, :id, :name %>
      </div>

      <!-- Agregar la entrada para seleccionar la categoría para dama -->
      <div class="form-group category-fields lady"> <!-- Para categorías de Dama -->
        <label>Categorías para Dama</label><br>
        <%= f.collection_select :category_id, Category.where(gender_id: Gender.find_by(name: 'Dama').id), :id, :category_type %>
      </div>

      <!-- Agregar la entrada para seleccionar la categoría para caballero -->

      <div class="form-group">
        <label>Colores</label>
        <div class="btn-group-toggle" data-toggle="buttons">
          <% @colors.each do |color| %>
            <% text_color = ["Negro", "Azul marino", "Verde Oliva"].include?(color.name) ? "white" : "black" %>
            <label class="btn btn-outline-primary m-2" style="background-color: <%= color.hex_code %>; color: <%= text_color %>">
              <%= f.check_box :color_ids, { multiple: true }, color.id, nil %>
              <%= color.name %>
            </label>
          <% end %>
        </div>
      </div>
      <br>
      <label>Tallas</label>
      <div class="form-group d-flex flex-wrap">
        <%= f.collection_check_boxes :size_ids, Size.all, :id, :measure do |b| %>
          <div class="form-check mb-2 mr-2">
            <%= b.check_box class: "form-check-input" %>
            <%= b.label class: "form-check-label" %>
          </div>
        <% end %>
      </div>


      <div class="row d-flex justify-content-center">
        <div class="col-2">
          <%= f.submit product.new_record? ? "Crear" : "Actualizar", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h1 class="text-center">Solo los propietarios pueden crear nuevos productos.</h1>
<% end %>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="ruta m-3">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "Inicio", root_path, class: "text-decoration-none text-black" %></li>
      <li class="breadcrumb-item active" aria-current="page">Productos</li>
    </ol>
  </nav>
</div>

<div class="categories-bar justify-content-center">
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="categoryDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Categorías
    </button>
    <ul class="dropdown-menu" aria-labelledby="categoryDropdown">
      <% @categories.each do |category| %>
        <% if category.products.where(availability: 'Disponible').exists? %>
          <% words = category.category_type.split(' ') %>
          <% truncated_category = words[0..-2].join(' ') %>
          <li class="dropdown-item" onclick="categoryFilter('<%= category.category_type %>')"><%= truncated_category %></li>
        <% end %>
      <% end %>
      <li><hr class="dropdown-divider"></li>
      <li class="dropdown-item" onclick="categoryFilter('all')">Todos los Productos</li>
      <% if user_signed_in? %>
        <%= link_to new_product_path, class: "btn btn-link p-0" do %>
          <li class="dropdown-item">Nuevo producto</li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>



<div class="products">
  <% @products.each do |product| %>
    <% if user_signed_in? || product.availability == "Disponible" %>
      <div class="card" data-categories="<%= product.category.category_type %>">
        <a href="<%= product_path(product) %>">
          <% if product.photos.any? %>
            <%= cl_image_tag product.photos.first.url, class: "card-img-top product-image" %>
          <% else %>
            <%= image_tag "logo_negro.png", class: "card-img-top product-image" %>
          <% end %>
        </a>
        <div class="card-body" style="<%= product.availability == 'No disponible' ? 'background-color: rgb(255, 0, 0);' : '' %>" >
          <h6 class="card-text name"><strong><%= product.name %></strong></h6>
          <% if product.availability == "No disponible" %>
            <h6 class="card-text"><%= product.availability %></h6>
          <% end %>
          <div class="price"><%= number_to_currency(product.price, unit: '$', format: '%u%n') %></div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<script>
  function categoryFilter(filter) {
    let categoryCards = document.getElementsByClassName('card');
    for (let i = 0; i < categoryCards.length; i++) {
      let categoryCard = categoryCards[i];
      let categoryType = categoryCard.getAttribute('data-categories');
      if (categoryType === filter || filter === 'all') {
        categoryCard.style.display = 'block';
      } else {
        categoryCard.style.display = 'none';
      }
    }
  }
</script>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="ruta m-3">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "Inicio", root_path, class: "text-decoration-none text-black" %></li>
      <% if @product.gender.name == 'Dama' %>
        <li class="breadcrumb-item"><%= link_to "Productos", products_path(gender: 'lady'), class: "text-decoration-none text-black" %></li>
      <% elsif @product.gender.name == 'Caballero' %>
        <li class="breadcrumb-item"><%= link_to "Productos", products_path(gender: 'gentleman'), class: "text-decoration-none text-black" %></li>
      <% end %>
      <li class="breadcrumb-item active" aria-current="page"><%= @product.name %></li>
    </ol>
  </nav>
</div>
<div class="container container-product d-flex justify-content-center align-items-center">
  <div class="row product">
    <div class="col-12 col-lg-7 mt-2">
      <div class="m-3">
        <div id="carouselExample" class="carousel slide carousel-css">
            <div class="carousel-inner">
              <% if @product.photos.empty? %>
                <div class="carousel-item active" style="transition: transform .6s ease-in-out">
                  <%= image_tag "logo_negro.png", class: "d-block mx-auto", style: "max-width: 300px; max-height: 300px;", alt: "Producto sin imagen" %>
                </div>
              <% else %>
                <% @product.photos.each_with_index do |photo, index| %>
                  <div class="carousel-item <%= 'active' if index.zero? %>" style="transition: transform .6s ease-in-out">
                    <%= cl_image_tag photo.url, class: "d-block mx-auto", style: "max-width: 300px; max-height: 300px;", alt: "Imagen de producto" %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="d-flex justify-content-between">
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          </div>
      </div>
    </div>
    <div class="col-12 col-lg-5 information">
      <div class="m-3">
        <h5 class="card-title mb-1"><strong><%= @product.name %> </strong></h5>
        <hr class="border-dark">
        <p class="card-text mb-2"><%= @product.description %></p>
        <p class="card-text mb-2">Precio unitario: <%= number_to_currency(@product.price, unit: '$', format: '%u%n') %></p>
        <p class="card-text mb-2">Precio a partir de <%= @product.quantity %> unidades: <%= number_to_currency(@product.wholesale_price, unit: '$', format: '%u%n') %></p>
        <p class="card-text mb-2">Disponible en las siguientes Tallas</p>
        <div class="card-text mb-2">
          <% @product.sizes.each do |size| %>
            <span class="badge bg-secondary me-2"><%= size.measure %></span>
          <% end %>
        </div>
        <p class="card-text mb-2">Disponible en los siguientes colores</p>
        <div class="card-text mb-2">
          <% @product.colors.each do |color| %>
            <% if color.name == "Blanco" %>
              <span class="badge bg-color me-2" style="background-color: <%= color.hex_code %>; color: black;">
                <%= color.name %>
              </span>
            <% else %>
              <span class="badge bg-color me-2" style="background-color: <%= color.hex_code %>; color: #ffffff;">
                <%= color.name %>
              </span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="d-flex">
  <% if user_signed_in? %>
    <div>
      <%= link_to "Actualizar", edit_product_path(@product), class: "btn btn-primary" %>
    </div>
  <% end %>
  <div class="whatsaap">
    <a href="https://api.whatsapp.com/send?phone=573155127061&text=<%= CGI.escape("#{product_url(@product)}
¡Hola! Estoy interesado en el producto: #{@product.name}.
Puedes brindarme más información?") %>" target="_blank">
      <button type="button" class="btn btn-dark"><i class="fa-brands fa-whatsapp" style="color: #ffffff;"></i> ¡Contactanos para Comprar!</button>
    </a>
  </div>
  <% if user_signed_in? %>
    <div>
      <%= link_to "Eliminar", product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="copyright d-flex">
    <li><a href="https://www.instagram.com/valenhernandez_z/" target="_blank"><i class="fab fa-instagram"></i></a></li>
    <li>COPYRIGHT ©2023. Todos los Derechos Reservados.</li>
  </ul>
  <div class="user">
    <% if user_signed_in? %>
      <%= link_to "Cerrar Sesión", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    <% else %>
      <%= link_to "¿Eres propietario?", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>